import Ionicons from '@expo/vector-icons/Ionicons';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';

import { AppHeader, AppText, MobilePage } from '@/components/ui';
import { MediaGallery } from '@/components/media-gallery';
import { colors, contentPadding, shadow } from '@/constants/theme';
import { useSession } from '@/context/session.remote';
import { PrimaryTabScene } from '@/navigation/primary-navigation';

export default function PortfolioScreen() {
  const { certifications, currentAccount, portfolioItems } = useSession();
  const items = portfolioItems.filter((item) => item.studentId === currentAccount?.id);
  const certs = certifications.filter((item) => item.studentId === currentAccount?.id);
  if (!currentAccount || currentAccount.role !== 'student') return <MobilePage><AppHeader title="Portfolio" onBack={() => router.back()} /><View style={styles.empty}><AppText>Portfolios are available to Student Designers.</AppText></View></MobilePage>;
  return <PrimaryTabScene active="portfolio"><MobilePage><StatusBar style="light" /><AppHeader title="My Portfolio" /><ScrollView showsHorizontalScrollIndicator={false} contentContainerStyle={styles.content}><View style={styles.headingRow}><AppText weight="semibold" style={styles.heading}>Work Samples</AppText><Pressable onPress={() => router.push('/portfolio/new')} style={styles.addButton}><AppText weight="medium" style={styles.addButtonText}>+ Add</AppText></Pressable></View>{items.length ? items.map((item) => <View key={item.id} style={styles.card}><View style={styles.art}><Ionicons name={item.sourceProjectId ? 'briefcase' : 'images-outline'} size={30} color={colors.red} /></View><View style={{ flex: 1 }}><AppText weight="semibold" style={styles.title}>{item.title}</AppText><AppText style={styles.category}>{item.category}</AppText><AppText style={styles.copy}>{item.description}</AppText><MediaGallery targetType="portfolio" targetId={item.id} />{item.sourceProjectId ? <View style={styles.clientBadge}><AppText weight="medium" style={styles.clientBadgeText}>Completed Client Project</AppText></View> : null}</View></View>) : <Empty text="No portfolio items yet." />}<View style={styles.headingRow}><AppText weight="semibold" style={styles.heading}>Certifications</AppText><Pressable onPress={() => router.push('/certifications/new')} style={styles.addButton}><AppText weight="medium" style={styles.addButtonText}>+ Add</AppText></Pressable></View>{certs.length ? certs.map((cert) => <View key={cert.id} style={styles.cert}><Ionicons name="ribbon" size={28} color={colors.gold} /><View><AppText weight="semibold">{cert.name}</AppText><AppText style={styles.category}>{cert.issuer} · {cert.year}</AppText><MediaGallery targetType="certification" targetId={cert.id} /></View></View>) : <Empty text="No certifications added yet." />}</ScrollView></MobilePage></PrimaryTabScene>;
}
function Empty({ text }: { text: string }) { return <View style={styles.emptyCard}><AppText style={styles.category}>{text}</AppText></View>; }
const styles = StyleSheet.create({ content: { padding: contentPadding, paddingBottom: 40 }, empty: { flex: 1, alignItems: 'center', justifyContent: 'center' }, headingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 20, marginBottom: 8 }, heading: { fontSize: 19 }, addButton: { backgroundColor: colors.red, borderRadius: 8, paddingVertical: 6, paddingHorizontal: 12 }, addButtonText: { color: colors.white, fontSize: 12 }, card: { flexDirection: 'row', gap: 13, backgroundColor: colors.white, borderRadius: 13, padding: 13, marginBottom: 14, ...shadow }, art: { width: 70, height: 70, borderRadius: 10, backgroundColor: colors.blush, alignItems: 'center', justifyContent: 'center' }, title: { fontSize: 15 }, category: { color: colors.muted, fontSize: 10, marginTop: 3 }, copy: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 6 }, clientBadge: { alignSelf: 'flex-start', backgroundColor: colors.greenSoft, borderRadius: 10, paddingHorizontal: 8, paddingVertical: 4, marginTop: 8 }, clientBadgeText: { color: colors.green, fontSize: 8 }, cert: { flexDirection: 'row', alignItems: 'center', gap: 13, backgroundColor: colors.white, borderRadius: 12, padding: 14, marginBottom: 14, ...shadow }, emptyCard: { minHeight: 75, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, borderRadius: 12 } });
