import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { Alert, FlatList, Pressable, StyleSheet, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';

import { AppHeader, AppText, MobilePage, PrimaryButton } from '@/components/ui';
import { colors, contentPadding, shadow } from '@/constants/theme';
import { formatPeso } from '@/data/fixtures';
import { Proposal, useSession } from '@/context/session';

export default function ProposalsScreen() {
  const { postId } = useLocalSearchParams<{ postId: string }>();
  const { accounts, currentAccount, decideProposal, profiles, projectPosts, proposals, verifications } = useSession();
  const post = projectPosts.find((item) => item.id === postId);
  const visible = proposals.filter((item) => item.projectPostId === postId && item.status !== 'withdrawn');
  if (!post || post.clientId !== currentAccount?.id) return <MobilePage><StatusBar style="light" /><AppHeader title="Proposals" onBack={() => router.back()} /><View style={styles.empty}><AppText>This proposal list is available only to the project Client.</AppText></View></MobilePage>;
  const decide = (proposal: Proposal, accept: boolean) => {
    const result = decideProposal(proposal.id, accept);
    if (!result.ok) return Alert.alert('Unable to update proposal', result.message);
    if (accept && result.bookingId) { Alert.alert('Proposal accepted', 'A shared project booking has been created. Demo funding is the next step.'); router.replace({ pathname: '/projects/[projectId]', params: { projectId: result.bookingId } }); }
    else Alert.alert('Proposal rejected', 'The Student Designer has been notified locally.');
  };
  return <MobilePage><StatusBar style="light" /><AppHeader title="Compare Proposals" onBack={() => router.back()} /><View style={styles.summary}><AppText weight="semibold" style={styles.projectTitle}>{post.title}</AppText><AppText style={styles.muted}>{visible.length} proposal{visible.length === 1 ? '' : 's'} · {formatPeso(post.budget)} posted budget</AppText></View><FlatList data={visible} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => { const student = accounts.find((account) => account.id === item.studentId); const profile = profiles.find((candidate) => candidate.accountId === item.studentId); const verified = verifications.find((candidate) => candidate.studentId === item.studentId)?.status === 'verified'; return <View style={styles.card}><Pressable onPress={() => router.push({ pathname: '/profiles/[userId]', params: { userId: item.studentId } })} style={styles.person}><View style={styles.avatar}><Ionicons name="person" size={24} color={colors.burgundy} /></View><View style={{ flex: 1 }}><AppText weight="semibold">{student?.name ?? 'Student Designer'}</AppText><AppText style={styles.muted}>{profile?.skills.slice(0, 3).join(' · ') || 'View public profile'}</AppText></View>{verified ? <View style={styles.verified}><Ionicons name="checkmark-circle" size={15} color={colors.green} /><AppText style={styles.verifiedText}>Verified</AppText></View> : null}</Pressable><AppText style={styles.cover}>{item.coverLetter}</AppText><View style={styles.bid}><View><AppText style={styles.muted}>Proposal</AppText><AppText weight="bold">{formatPeso(item.amount)}</AppText></View><View><AppText style={styles.muted}>Delivery</AppText><AppText weight="bold">{item.deliveryDays} days</AppText></View><View style={styles.state}><AppText weight="medium" style={styles.stateText}>{item.status}</AppText></View></View>{item.status === 'submitted' && post.status === 'open' ? <View style={styles.actions}><Pressable onPress={() => decide(item, false)} style={styles.reject}><AppText weight="semibold" style={{ color: colors.red }}>Reject</AppText></Pressable><PrimaryButton title="Accept" onPress={() => decide(item, true)} style={{ flex: 1 }} /></View> : null}</View>; }} ListEmptyComponent={<View style={styles.empty}><Ionicons name="document-text-outline" size={52} color={colors.muted} /><AppText weight="semibold" style={{ marginTop: 12 }}>No proposals yet</AppText><AppText style={styles.muted}>Verified Student Designer proposals will appear here.</AppText></View>} /></MobilePage>;
}

const styles = StyleSheet.create({ summary: { paddingHorizontal: contentPadding, paddingTop: 16 }, projectTitle: { fontSize: 19 }, muted: { color: colors.muted, fontSize: 10, marginTop: 3 }, list: { flexGrow: 1, padding: contentPadding, gap: 14 }, card: { backgroundColor: colors.white, borderRadius: 14, padding: 15, ...shadow }, person: { flexDirection: 'row', alignItems: 'center', gap: 10 }, avatar: { width: 46, height: 46, borderRadius: 23, backgroundColor: colors.blush, alignItems: 'center', justifyContent: 'center' }, verified: { flexDirection: 'row', alignItems: 'center', gap: 3 }, verifiedText: { color: colors.green, fontSize: 8 }, cover: { fontSize: 12, lineHeight: 19, marginTop: 14 }, bid: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: colors.blush, borderRadius: 10, padding: 12, marginTop: 14 }, state: { backgroundColor: colors.white, borderRadius: 8, paddingHorizontal: 8, paddingVertical: 5 }, stateText: { color: colors.burgundy, fontSize: 8, textTransform: 'capitalize' }, actions: { flexDirection: 'row', gap: 9, marginTop: 13 }, reject: { flex: 1, minHeight: 50, borderWidth: 1, borderColor: colors.border, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, empty: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 30 } });
