import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { FlatList, Pressable, StyleSheet, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';

import { AppHeader, AppText, MobilePage } from '@/components/ui';
import { colors, contentPadding, shadow } from '@/constants/theme';
import { formatPeso } from '@/data/fixtures';
import { useSession } from '@/context/session';

export default function DemoWalletScreen() {
  const { bookings, currentAccount, ledger } = useSession();
  const entries = currentAccount ? ledger.filter((item) => item.userId === currentAccount.id) : [];
  const holds = entries.filter((item) => item.type === 'hold').reduce((total, item) => total + item.amount, 0);
  const releases = entries.filter((item) => item.type === 'release').reduce((total, item) => total + item.amount, 0);
  return <MobilePage><StatusBar style="light" /><AppHeader title="Demo Wallet" onBack={() => router.back()} /><View style={styles.notice}><Ionicons name="flask-outline" size={22} color={colors.burgundy} /><AppText style={styles.noticeText}>Simulation only. No card, bank account, payment processor, escrow, or real money is connected.</AppText></View><View style={styles.summary}><Summary label="Demo funds reserved" value={holds} /><Summary label="Simulated earnings released" value={releases} /></View><AppText weight="semibold" style={styles.heading}>Local Ledger</AppText><FlatList data={entries} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} renderItem={({ item }) => { const project = bookings.find((candidate) => candidate.id === item.projectId); return <Pressable onPress={() => router.push({ pathname: '/projects/[projectId]', params: { projectId: item.projectId } })} style={styles.row}><View style={[styles.icon, item.type === 'release' && { backgroundColor: colors.greenSoft }]}><Ionicons name={item.type === 'hold' ? 'lock-closed-outline' : 'checkmark-circle-outline'} size={23} color={item.type === 'hold' ? colors.red : colors.green} /></View><View style={{ flex: 1 }}><AppText weight="semibold">{item.type === 'hold' ? 'Demo hold' : 'Simulated release'}</AppText><AppText style={styles.detail}>{project?.title ?? 'Project'} · {new Date(item.createdAt).toLocaleDateString()}</AppText></View><AppText weight="bold">{formatPeso(item.amount)}</AppText></Pressable>; }} ListEmptyComponent={<View style={styles.empty}><Ionicons name="wallet-outline" size={50} color={colors.muted} /><AppText weight="semibold" style={{ marginTop: 11 }}>No demo transactions yet</AppText><AppText style={styles.detail}>Funding and approval events will create local ledger entries.</AppText></View>} /></MobilePage>;
}
function Summary({ label, value }: { label: string; value: number }) { return <View style={styles.summaryItem}><AppText weight="bold" style={styles.amount}>{formatPeso(value)}</AppText><AppText style={styles.summaryLabel}>{label}</AppText></View>; }
const styles = StyleSheet.create({ notice: { margin: contentPadding, marginBottom: 8, backgroundColor: colors.blush, borderRadius: 12, padding: 13, flexDirection: 'row', gap: 9 }, noticeText: { flex: 1, color: colors.burgundy, fontSize: 9, lineHeight: 15 }, summary: { flexDirection: 'row', gap: 9, paddingHorizontal: contentPadding }, summaryItem: { flex: 1, minHeight: 94, borderRadius: 13, padding: 13, justifyContent: 'center', backgroundColor: colors.white, ...shadow }, amount: { fontSize: 19 }, summaryLabel: { color: colors.muted, fontSize: 8, lineHeight: 13, marginTop: 5 }, heading: { fontSize: 17, marginHorizontal: contentPadding, marginTop: 23 }, list: { flexGrow: 1, paddingHorizontal: contentPadding, paddingBottom: 30 }, row: { minHeight: 83, flexDirection: 'row', alignItems: 'center', gap: 11, borderBottomWidth: 1, borderBottomColor: colors.border }, icon: { width: 45, height: 45, borderRadius: 23, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.blush }, detail: { color: colors.muted, fontSize: 9, marginTop: 4, textAlign: 'center' }, empty: { alignItems: 'center', paddingTop: 65 } });
