import { createContext, PropsWithChildren, ReactNode, useContext } from 'react';

export type AppLanguage = 'English' | 'Filipino';

const filipino: Record<string, string> = {
  'Account': 'Account', 'Preferences': 'Mga Kagustuhan', 'Support': 'Suporta',
  'Edit Profile': 'I-edit ang Profile', 'Change Password': 'Palitan ang Password', 'Demo Wallet': 'Demo Wallet',
  'Notification Badges': 'Mga Badge ng Notification', 'Language': 'Wika', 'Dark Mode': 'Dark Mode',
  'Connected Services': 'Mga Nakakonektang Serbisyo', 'Help Center': 'Help Center',
  'Terms & Conditions': 'Mga Tuntunin at Kondisyon', 'Privacy Policy': 'Patakaran sa Privacy',
  'Log Out': 'Mag-log Out', 'Settings': 'Mga Setting', 'English': 'Ingles', 'Filipino': 'Filipino',
  'Choose the language used throughout SkillFlow.': 'Piliin ang wikang gagamitin sa buong SkillFlow.',
  'Home': 'Home', 'Projects': 'Mga Proyekto', 'Portfolio': 'Portfolio', 'Messages': 'Mga Mensahe',
  'Saved': 'Naka-save', 'Profile': 'Profile', 'Discover': 'Maghanap', 'Create': 'Gumawa',
  'Notifications': 'Mga Notification', 'All': 'Lahat', 'Unread': 'Hindi Pa Nabasa', 'Mentions': 'Mga Banggit',
  'No notifications here.': 'Walang notification dito.', 'Marketplace': 'Marketplace',
  'Search services': 'Maghanap ng mga serbisyo', 'Clear': 'I-clear', 'Results': 'Mga Resulta',
  'Student Designer': 'Student Designer', 'Client': 'Kliyente', 'Continue': 'Magpatuloy',
  'Sign In': 'Mag-sign In', 'Register': 'Magrehistro', 'Forgot Password?': 'Nakalimutan ang Password?',
  'Email': 'Email', 'Password': 'Password', 'Name': 'Pangalan', 'Location': 'Lokasyon',
  'Save Changes': 'I-save ang mga Pagbabago', 'Cancel': 'Kanselahin', 'Delete': 'Tanggalin',
  'Back': 'Bumalik', 'Go back': 'Bumalik', 'Submit': 'Isumite', 'Retry': 'Subukan Muli',
  'Student Verification': 'Pagpapatunay ng Estudyante', 'Demo Approved': 'Demo Approved',
  'Checking Demo Submission': 'Sinusuri ang Demo Submission', 'School or Campus': 'Paaralan o Campus',
  'Student Number': 'Numero ng Estudyante', 'Program or Strand': 'Programa o Strand',
  'Grade Level': 'Antas ng Baitang', 'Graduation Year': 'Taon ng Pagtatapos',
  'Fictional Student ID Sample': 'Kathang-isip na Sample Student ID',
  'Submit for Verification': 'Isumite para sa Pagpapatunay', 'Resubmit Verification': 'Isumiteng Muli',
  'Return to Profile': 'Bumalik sa Profile', 'Demo Verified Student': 'Demo Verified na Estudyante',
  'Services': 'Mga Serbisyo', 'My Services': 'Aking Mga Serbisyo', 'Post a Project': 'Mag-post ng Proyekto',
  'Browse Services': 'Mag-browse ng mga Serbisyo', 'Find Designers': 'Maghanap ng mga Designer',
  'View All': 'Tingnan Lahat', 'Your Projects': 'Iyong Mga Proyekto', 'Recent Projects': 'Mga Kamakailang Proyekto',
  'Career Readiness': 'Kahandaan sa Karera', 'Career Readiness Score': 'Iskor sa Kahandaan sa Karera',
  'Project Booking': 'Booking ng Proyekto', 'Project Details': 'Detalye ng Proyekto', 'Budget': 'Badyet',
  'Delivery': 'Paghahatid', 'Status': 'Katayuan', 'Open Project Messages': 'Buksan ang Mensahe ng Proyekto',
  'Request Sent': 'Naipadala ang Kahilingan', 'Accepted': 'Tinanggap', 'Declined': 'Tinanggihan',
  'Cancelled': 'Kinansela', 'Demo Funds Reserved': 'Nakareserba ang Demo Funds', 'In Progress': 'Ginagawa',
  'Delivery Submitted': 'Naisumite ang Delivery', 'Revision Requested': 'Humiling ng Pagbabago',
  'Completed': 'Nakumpleto', 'Reviewed': 'Nasuri', 'Start Work': 'Simulan ang Trabaho',
  'Submit Delivery': 'Isumite ang Delivery', 'Submit Revision': 'Isumite ang Pagbabago',
  'Approve and Release Demo Earnings': 'Aprubahan at Ilabas ang Demo Earnings',
  'Request Revision': 'Humiling ng Pagbabago', 'Submit Review': 'Isumite ang Review',
  'Cancel Request': 'Kanselahin ang Kahilingan', 'Demo Checkout': 'Demo Checkout',
  'Demo amount': 'Demo na halaga', 'Demo e-wallet': 'Demo e-wallet', 'Demo bank transfer': 'Demo bank transfer',
  'Demo cash': 'Demo cash', 'Confirm Simulated Payment': 'Kumpirmahin ang Simulated Payment',
  'Cancel and Refund Demo Funds': 'Kanselahin at I-refund ang Demo Funds',
  'Demo Payment Receipt': 'Demo Payment Receipt', 'Amount': 'Halaga', 'Method': 'Paraan',
  'Demo Transaction History': 'Kasaysayan ng Demo Transaction', 'Total demo holds': 'Kabuuang demo hold',
  'Demo refunds': 'Mga demo refund', 'Simulated earnings released': 'Inilabas na simulated earnings',
  'No demo transactions yet': 'Wala pang demo transaction', 'Project': 'Proyekto',
  'AI Project Mentor': 'AI Project Mentor', 'New Conversation': 'Bagong Usapan', 'Conversation History': 'Kasaysayan ng Usapan',
  'Send': 'Ipadala', 'Try again': 'Subukan muli', 'Delete conversation': 'Tanggalin ang usapan',
  'Help': 'Tulong', 'SkillFlow Demo Help': 'Tulong sa SkillFlow Demo',
  'SkillFlow Demo Privacy Notice': 'Abiso sa Privacy ng SkillFlow Demo',
  'SkillFlow Demonstration Terms': 'Mga Tuntunin ng SkillFlow Demonstration',
  'Academic demonstration copy': 'Nilalaman para sa akademikong demonstration',
  'No payment collection': 'Walang pagkolekta ng bayad', 'Simulated verification': 'Simulated na pagpapatunay',
  'AI Mentor': 'AI Mentor', 'Safe demonstration data': 'Ligtas na demonstration data',
  'Cloud application records': 'Mga cloud application record', 'Authentication provider': 'Authentication provider',
  'Deletion and reset controls': 'Mga kontrol sa pagtanggal at pag-reset', 'Appropriate use': 'Wastong paggamit',
  'Purpose': 'Layunin', 'Projects and payments': 'Mga proyekto at bayad', 'Demo accounts and cloud data': 'Mga demo account at cloud data',
  'Loading…': 'Naglo-load…', 'Saving…': 'Sine-save…', 'Submitting…': 'Isinusumite…',
  'Action unavailable': 'Hindi available ang aksyon', 'Required': 'Kailangan',
  'Log In': 'Mag-log In', 'Sign Out': 'Mag-sign Out', 'Signing in...': 'Nagsa-sign in...',
  'Signing out…': 'Nagsa-sign out…', 'Please wait…': 'Pakihintay…', 'Display Name': 'Pangalan na Ipapakita',
  'Bio': 'Tungkol sa Sarili', 'Organization': 'Organisasyon', 'School': 'Paaralan', 'Program': 'Programa',
  'Grade': 'Baitang', 'Skills': 'Mga Kasanayan', 'Category': 'Kategorya', 'Description': 'Paglalarawan',
  'Deadline': 'Huling Araw', 'Revisions': 'Mga Pagbabago', 'Rating': 'Rating', 'Reviews': 'Mga Review',
  'About': 'Tungkol Dito', 'Work Samples': 'Mga Halimbawa ng Gawa', 'Certifications': 'Mga Sertipikasyon',
  'Project Title': 'Pamagat ng Proyekto', 'Project Description': 'Paglalarawan ng Proyekto',
  'Required Skills (comma separated)': 'Mga Kailangang Kasanayan (paghiwalayin ng kuwit)',
  'Deadline (YYYY-MM-DD)': 'Huling Araw (YYYY-MM-DD)', 'Publish Project': 'I-publish ang Proyekto',
  'Edit Project': 'I-edit ang Proyekto', 'Discover Projects': 'Maghanap ng mga Proyekto',
  'Search title, category, or skill': 'Maghanap ng pamagat, kategorya, o kasanayan',
  'Service Title': 'Pamagat ng Serbisyo', 'Short Description': 'Maikling Paglalarawan',
  'Full Description': 'Buong Paglalarawan', 'Starting Price': 'Panimulang Presyo',
  'Delivery Days': 'Mga Araw ng Paghahatid', 'Publish Service': 'I-publish ang Serbisyo',
  'Create Service': 'Gumawa ng Serbisyo', 'Edit Service': 'I-edit ang Serbisyo', 'Service': 'Serbisyo',
  'Book Service': 'I-book ang Serbisyo', 'Send Request': 'Ipadala ang Kahilingan',
  'Request This Service': 'Hilingin ang Serbisyong Ito', 'Back to Marketplace': 'Bumalik sa Marketplace',
  'Add Portfolio Item': 'Magdagdag sa Portfolio', 'Add to Portfolio': 'Idagdag sa Portfolio',
  'Add Certification': 'Magdagdag ng Sertipikasyon', 'Certification Name': 'Pangalan ng Sertipikasyon',
  'Issuer': 'Nagbigay', 'Year': 'Taon', 'Certification Evidence': 'Katibayan ng Sertipikasyon',
  'Profile Image': 'Larawan ng Profile', 'Save Profile': 'I-save ang Profile',
  'Comma-separated skills': 'Mga kasanayang pinaghihiwalay ng kuwit',
  'Tell clients or students about yourself…': 'Ipakilala ang iyong sarili sa mga kliyente o estudyante…',
  'Describe this image': 'Ilarawan ang larawang ito', 'Search services…': 'Maghanap ng mga serbisyo…',
  'Write a message…': 'Sumulat ng mensahe…', 'Message your AI mentor…': 'Magpadala ng mensahe sa AI mentor…',
  'You can type your next message…': 'Maaari mong i-type ang susunod mong mensahe…',
  'Describe your project…': 'Ilarawan ang iyong proyekto…',
  'Describe what the client will receive…': 'Ilarawan kung ano ang matatanggap ng kliyente…',
  'Describe the goal, deliverables, and expectations…': 'Ilarawan ang layunin, ihahatid, at mga inaasahan…',
  'Describe the work, skills, and outcome…': 'Ilarawan ang gawa, mga kasanayan, at resulta…',
  'Explain why you are a good fit…': 'Ipaliwanag kung bakit angkop ka…', 'Proposed amount': 'Iminungkahing halaga',
  'Delivery days': 'Mga araw ng paghahatid', 'Submit Proposal': 'Isumite ang Proposal',
  'Proposals': 'Mga Proposal', 'Compare Proposals': 'Ihambing ang mga Proposal', 'Proposal': 'Proposal',
  'Accept': 'Tanggapin', 'Reject': 'Tanggihan', 'Verified': 'Napatunayan',
  'View public profile': 'Tingnan ang pampublikong profile',
  'Reset Password': 'I-reset ang Password', 'Email Address': 'Email Address', 'Recovery Code': 'Recovery Code',
  'New Password': 'Bagong Password', 'Confirm Password': 'Kumpirmahin ang Password',
  'Finish account setup': 'Tapusin ang pag-set up ng account', 'Creating profile…': 'Ginagawa ang profile…',
  'Finish connecting your account': 'Tapusin ang pagkonekta ng iyong account',
  'Retry connection': 'Subukang Kumonekta Muli', 'Your chats': 'Iyong mga usapan',
  'Open chat history': 'Buksan ang kasaysayan ng usapan', 'Improve an idea': 'Pagandahin ang ideya',
  'Review a design': 'Suriin ang disenyo', 'Build a palette': 'Gumawa ng color palette',
  'Polish a portfolio': 'Pagandahin ang portfolio', 'Submit Revised Delivery': 'Isumite ang Binagong Delivery',
  'Review Delivery': 'Suriin ang Delivery', 'Rate the Student': 'Bigyan ng Rating ang Estudyante',
  'Write a short review…': 'Sumulat ng maikling review…',
  'Revision instructions, if needed…': 'Mga tagubilin sa pagbabago, kung kailangan…',
  'Describe the completed work or demo file…': 'Ilarawan ang natapos na gawa o demo file…',
  'Choose a simulated payment method.': 'Pumili ng simulated na paraan ng pagbabayad.',
  'Confirmation creates a demo hold and receipt only.': 'Ang pagkumpirma ay gagawa lamang ng demo hold at resibo.',
  'No biography added yet.': 'Wala pang idinagdag na talambuhay.',
  'No portfolio items yet.': 'Wala pang laman ang portfolio.',
  'No certifications added yet.': 'Wala pang idinagdag na sertipikasyon.',
  'Completed Client Project': 'Nakumpletong Proyekto ng Kliyente',
  'How do I test both roles?': 'Paano ko susubukan ang dalawang role?',
  'Where is demonstration data stored?': 'Saan nakaimbak ang demonstration data?',
  'Who handles sign-in and recovery?': 'Sino ang nangangasiwa sa sign-in at recovery?',
  'Are payments real?': 'Totoo ba ang mga bayad?',
  'How does verification work?': 'Paano gumagana ang verification?',
  'Does the AI Mentor use an external AI?': 'Gumagamit ba ng external AI ang AI Mentor?',
  'How do I restart the demonstration?': 'Paano ko sisimulang muli ang demonstration?',
  'Create or use one Student Designer account and one Client account in the Clerk development instance. Log out and sign in to the other account to switch roles. Shared project data remains available in Convex Cloud.': 'Gumawa o gumamit ng isang Student Designer account at isang Client account sa Clerk development instance. Mag-log out at mag-sign in sa kabilang account para magpalit ng role. Mananatili sa Convex Cloud ang shared project data.',
  'Authenticated application records, including shared project data, are stored in Convex Cloud. Use fictional or non-sensitive information.': 'Ang authenticated application records, kabilang ang shared project data, ay nakaimbak sa Convex Cloud. Gumamit ng kathang-isip o hindi sensitibong impormasyon.',
  'Clerk processes authentication, email verification, OAuth when chosen, session data, and delivery of password-recovery email codes.': 'Pinoproseso ng Clerk ang authentication, email verification, OAuth kapag pinili, session data, at pagpapadala ng password recovery email codes.',
  'No. Holds, releases, balances, and earnings are clearly labeled simulations. Never enter card or banking information.': 'Hindi. Ang holds, releases, balances, at earnings ay malinaw na may label na simulation. Huwag maglagay ng card o banking information.',
  'The student submits a fictional sample form and image. The app briefly checks the demo submission, then marks it Demo Approved automatically. It does not verify identity or contact a school. Never enter a real student ID.': 'Nagsusumite ang estudyante ng kathang-isip na sample form at larawan. Sandaling sinusuri ng app ang demo submission at awtomatikong minamarkahan itong Demo Approved. Hindi nito vine-verify ang pagkakakilanlan o kinokontak ang paaralan. Huwag maglagay ng totoong student ID.',
  'Yes. Prompts are sent to OpenCode Go. When the AI service is unavailable, unsent messages can be retried. Prompts and conversation history are stored in Convex Cloud. Do not share personal, confidential, or client information.': 'Oo. Ipinapadala ang prompts sa OpenCode Go. Kapag hindi available ang AI service, maaaring subukang muli ang hindi naipadalang mensahe. Nakaimbak sa Convex Cloud ang prompts at conversation history. Huwag magbahagi ng personal, kumpidensyal, o impormasyon ng kliyente.',
  'There is no demo-reset action in Settings. Cloud-development seed resets are operator-only and limited to the designated demonstration seed namespace.': 'Walang demo reset action sa Settings. Operator lamang ang maaaring magsagawa ng cloud development seed reset at limitado ito sa nakatalagang demonstration seed namespace.',
  'When you are signed in, account profiles, projects, bookings, messages, saved services, mentor history, and other demonstration records are stored in Convex Cloud.': 'Kapag naka-sign in ka, ang mga profile, proyekto, booking, mensahe, naka-save na serbisyo, mentor history, at iba pang demonstration record ay nakaimbak sa Convex Cloud.',
  'Clerk processes account registration and sign-in, email verification, OAuth when you choose it, session data, and delivery of password-recovery email codes.': 'Pinoproseso ng Clerk ang account registration at sign-in, email verification, OAuth kapag pinili mo, session data, at pagpapadala ng password recovery email codes.',
  'SkillFlow does not collect card numbers, bank information, or real payments. All balances and transactions are simulated.': 'Hindi nangongolekta ang SkillFlow ng card number, bank information, o totoong bayad. Simulated ang lahat ng balance at transaction.',
  'Student Verification accepts fictional sample data and automatically marks a complete demo submission approved after a short check. It does not assess document authenticity or perform real identity verification.': 'Tumatanggap ang Student Verification ng kathang-isip na sample data at awtomatikong inaaprubahan ang kumpletong demo submission pagkatapos ng maikling pagsusuri. Hindi nito sinusuri ang pagiging tunay ng dokumento o nagsasagawa ng totoong identity verification.',
  'The AI Mentor sends prompts to OpenCode Go. When the AI service is unavailable, unsent messages can be retried. Prompts and conversation history are stored in Convex Cloud. Do not share personal, confidential, or client information.': 'Ipinapadala ng AI Mentor ang prompts sa OpenCode Go. Kapag hindi available ang AI service, maaaring subukang muli ang hindi naipadalang mensahe. Nakaimbak sa Convex Cloud ang prompts at conversation history. Huwag magbahagi ng personal, kumpidensyal, o impormasyon ng kliyente.',
  'You can clear mentor conversation history from the AI Mentor screen. Settings does not provide a general account-data deletion or demo-reset action. Cloud-development seed resets are operator-only and limited to the designated demonstration seed namespace.': 'Maaari mong burahin ang mentor conversation history sa AI Mentor screen. Walang pangkalahatang account data deletion o demo reset action sa Settings. Operator lamang ang maaaring magsagawa ng cloud development seed reset at limitado ito sa nakatalagang demonstration seed namespace.',
  'Use fictional or non-sensitive information. Do not enter real student IDs, financial credentials, confidential project files, or private client information.': 'Gumamit ng kathang-isip o hindi sensitibong impormasyon. Huwag maglagay ng totoong student ID, financial credential, kumpidensyal na project file, o pribadong impormasyon ng kliyente.',
  'SkillFlow is a functional academic demonstration for connecting student designers and clients. It is not a production marketplace.': 'Ang SkillFlow ay isang gumaganang akademikong demonstration na nag-uugnay sa mga student designer at kliyente. Hindi ito production marketplace.',
  'Authenticated application records are stored in Convex Cloud. Clerk processes registration, authentication, email verification, OAuth when chosen, session data, and password-recovery email delivery. Use sample information; do not enter real student IDs, financial credentials, confidential project files, private client information, or other sensitive personal or school data.': 'Nakaimbak sa Convex Cloud ang authenticated application records. Pinoproseso ng Clerk ang registration, authentication, email verification, OAuth kapag pinili, session data, at password recovery email. Gumamit ng sample information; huwag maglagay ng totoong student ID, financial credential, kumpidensyal na project file, pribadong impormasyon ng kliyente, o iba pang sensitibong personal o school data.',
  'Project bookings, balances, payment holds, releases, and verification are part of this academic demonstration. Ratings and in-app notifications are stored application records generated by demo activity. No real contract, payment, escrow, or transfer is created.': 'Bahagi ng akademikong demonstration na ito ang project booking, balance, payment hold, release, at verification. Ang rating at in-app notification ay mga application record na nalilikha ng demo activity. Walang totoong kontrata, bayad, escrow, o transfer na ginagawa.',
  'The mentor sends prompts to OpenCode Go. When the AI service is unavailable, unsent messages can be retried. Mentor conversation history is stored in Convex Cloud. Do not share personal, confidential, or client information. The guidance is not professional, academic, or employment advice.': 'Ipinapadala ng mentor ang prompts sa OpenCode Go. Kapag hindi available ang AI service, maaaring subukang muli ang hindi naipadalang mensahe. Nakaimbak sa Convex Cloud ang mentor conversation history. Huwag magbahagi ng personal, kumpidensyal, o impormasyon ng kliyente. Ang gabay ay hindi propesyonal, akademiko, o employment advice.',
  'Do not upload unlawful, confidential, harmful, or copyrighted material that you do not have permission to use.': 'Huwag mag-upload ng ilegal, kumpidensyal, mapaminsala, o copyrighted na materyal na wala kang pahintulot gamitin.',
  'Settings does not provide a general account-data deletion or demo-reset action. Cloud-development seed resets are operator-only and limited to the designated demonstration seed namespace.': 'Walang pangkalahatang account data deletion o demo reset action sa Settings. Operator lamang ang maaaring magsagawa ng cloud development seed reset at limitado ito sa nakatalagang demonstration seed namespace.',
  'Or type a different answer below.': 'O mag-type ng ibang sagot sa ibaba.',
  'Mentor is thinking?': 'Nag-iisip ang Mentor?',
  'Ask anything about your project, design, or portfolio, or start with a template.': 'Magtanong tungkol sa iyong proyekto, disenyo, o portfolio, o magsimula sa isang template.',
  'Don\'t share sensitive information': 'Huwag magbahagi ng sensitibong impormasyon',
  'Prompts are stored in Convex Cloud and sent to OpenCode Go. Do not share private or client information. If the AI service is unavailable, your unsent message can be retried.': 'Nakaimbak sa Convex Cloud at ipinapadala sa OpenCode Go ang prompts. Huwag magbahagi ng pribado o client information. Kapag hindi available ang AI service, maaaring subukang muli ang hindi naipadalang mensahe.',
  'New chat': 'Bagong usapan',
  'Delete this chat?': 'Tanggalin ang usapang ito?',
  'This permanently deletes the conversation and its messages.': 'Permanenteng tatanggalin nito ang usapan at mga mensahe.',
  'Career Readiness is available to Student Designers.': 'Available ang Career Readiness sa mga Student Designer.',
  'Your score updates automatically from your persisted SkillFlow demo activity.': 'Awtomatikong nag-a-update ang iyong score mula sa naka-save na SkillFlow demo activity.',
  'This is a transparent academic demonstration score, not an employment assessment or guarantee.': 'Ito ay malinaw na academic demonstration score at hindi employment assessment o garantiya.',
  'Score Breakdown': 'Detalye ng Score',
  'How it is calculated': 'Paano ito kinakalkula',
  'Profile 15 ? Simulated verification 15 ? Portfolio 20 ? Completed projects 25 ? Client ratings 15 ? Certifications 10': 'Profile 15 ? Simulated verification 15 ? Portfolio 20 ? Nakumpletong proyekto 25 ? Client rating 15 ? Sertipikasyon 10',
  'Every category is capped. Adding extra records cannot raise the total beyond 100.': 'May limit ang bawat kategorya. Hindi tataas sa 100 ang kabuuan kahit magdagdag ng records.',
  'Clerk securely manages your password. SkillFlow never stores it locally.': 'Ligtas na pinamamahalaan ng Clerk ang iyong password. Hindi ito iniimbak ng SkillFlow sa device.',
  'Active Projects': 'Mga Aktibong Proyekto',
  'Synced with SkillFlow Cloud': 'Naka-sync sa SkillFlow Cloud',
  'Quick Actions': 'Mabilis na Aksyon',
  'No project activity yet.': 'Wala pang project activity.',
  'Post a project or request a student service to begin.': 'Mag-post ng proyekto o humiling ng student service para magsimula.',
  'Funding, refund, and approval events will create simulated ledger entries.': 'Ang funding, refund, at approval events ay gagawa ng simulated ledger entries.',
  'Simulation only. No card, bank account, payment processor, escrow, or real money is connected.': 'Simulation lamang. Walang konektadong card, bank account, payment processor, escrow, o totoong pera.',
  'Welcome back!': 'Maligayang pagbabalik!',
  'Sign in to continue': 'Mag-sign in para magpatuloy',
  'Sign Up': 'Mag-sign Up',
  'or': 'o',
  'Filters': 'Mga Filter',
  'Clear all': 'I-clear lahat',
  'Saved services only': 'Mga naka-save na serbisyo lamang',
  'Completing sign-in': 'Tinatapos ang sign-in',
  'Securely returning you to SkillFlow?': 'Ligtas kang ibinabalik sa SkillFlow?',
  'I agree to the': 'Sumasang-ayon ako sa',
  'and': 'at',
  'Configuration looks valid': 'Maayos ang configuration',
  'Clerk authentication and Convex Cloud are configured for this build. Public client configuration is bundled with the app; protected deployment secrets remain server-side.': 'Naka-configure ang Clerk authentication at Convex Cloud para sa build na ito. Kasama sa app ang public client configuration; nananatili sa server ang protected deployment secrets.',
  'Dark mode is active throughout SkillFlow. This preference is stored in Convex Cloud and restored when you sign in again.': 'Aktibo ang dark mode sa buong SkillFlow. Nakaimbak ang preference na ito sa Convex Cloud at ibinabalik kapag nag-sign in ka muli.',
  'Development demo resets are operator-only and never run from the mobile app.': 'Operator lamang ang maaaring mag-reset ng development demo at hindi ito ginagawa sa mobile app.',
  'Earnings Overview': 'Buod ng Earnings',
  'Simulated Earnings': 'Simulated na Earnings',
  'No project requests yet': 'Wala pang project request',
  'Recommended project': 'Inirerekomendang proyekto',
  'Student verification is only available to Student Designer accounts.': 'Available lamang ang student verification sa mga Student Designer account.',
  'The sample submission passed the automatic demo check. No school or identity verification was performed.': 'Pumasa ang sample submission sa automatic demo check. Walang school o identity verification na isinagawa.',
  'The app is completing an automatic demo check. It checks the sample submission flow, not the authenticity of a student ID. No school is contacted.': 'Tinatapos ng app ang automatic demo check. Sinusuri nito ang sample submission flow at hindi ang pagiging tunay ng student ID. Walang paaralang kinokontak.',
  'Demo only. Upload a clearly fictional sample image. Never upload a real student ID or real student information.': 'Demo lamang. Mag-upload ng malinaw na kathang-isip na sample image. Huwag mag-upload ng totoong student ID o impormasyon.',
  'Verification rejected': 'Tinanggihan ang verification',
  'Choose from Gallery': 'Pumili sa Gallery',
  'Take Photo': 'Kumuha ng Larawan',
  'JPEG, PNG, WebP, or phone image. SkillFlow removes metadata, limits the longest edge to 2000 px, and rejects processed files over 5 MB.': 'JPEG, PNG, WebP, o phone image. Tinatanggal ng SkillFlow ang metadata, nililimitahan sa 2000 px ang pinakamahabang gilid, at tinatanggihan ang processed file na lampas 5 MB.',
  'Image unavailable': 'Hindi available ang larawan',
  'Client project brief': 'Project brief ng kliyente',
  'Publishing opens this brief for authenticated Student Designers. Payment remains simulated.': 'Kapag na-publish, makikita ito ng authenticated Student Designers. Simulated pa rin ang payment.',
  'Save Draft': 'I-save ang Draft',
  'Archive Project': 'I-archive ang Proyekto',
  'Unable to save project': 'Hindi ma-save ang proyekto',
  'App setup required': 'Kailangan ang app setup',
  'Add the following matching public values to an ignored .env.local file, then restart Expo to connect Clerk and Convex Cloud:': 'Idagdag ang sumusunod na matching public values sa ignored .env.local file, pagkatapos ay i-restart ang Expo para ikonekta ang Clerk at Convex Cloud:',
  'Never place Convex admin keys, Clerk secret keys, or deployment credentials in EXPO_PUBLIC_* variables.': 'Huwag ilagay ang Convex admin keys, Clerk secret keys, o deployment credentials sa EXPO_PUBLIC_* variables.',
  'Only Student Designers can manage services.': 'Student Designers lamang ang maaaring mamahala ng serbisyo.',
  'You can only edit your own services.': 'Sarili mong serbisyo lamang ang maaari mong i-edit.',
  'Demo Verified Student ? publishing enabled': 'Demo Verified Student ? maaaring mag-publish',
  'Verification required to publish': 'Kailangan ang verification para mag-publish',
  'You may save a draft now or complete the simulated verification.': 'Maaari kang mag-save ng draft ngayon o kumpletuhin ang simulated verification.',
  'Archive Service': 'I-archive ang Serbisyo',
  'Showcase Your Skills, Connect with Clients.': 'Ipakita ang Iyong Kasanayan, Kumonekta sa mga Kliyente.',
  'Your sign-in succeeded, but SkillFlow could not validate the secure backend session. Check your connection and try again.': 'Matagumpay ang sign-in, ngunit hindi ma-validate ng SkillFlow ang secure backend session. Suriin ang koneksyon at subukang muli.',
  'Choose your permanent SkillFlow role. This controls server-side access and cannot be switched from the login screen.': 'Piliin ang permanenteng SkillFlow role. Kinokontrol nito ang server-side access at hindi ito mapapalitan sa login screen.',
  'Connected services need attention': 'Kailangang ayusin ang connected services',
  'No project conversations': 'Wala pang project conversation',
  'A conversation becomes available when a service request or project is created.': 'Magiging available ang usapan kapag may service request o nagawang proyekto.',
  'Start the conversation': 'Simulan ang usapan',
  'Messages sync through the shared SkillFlow development backend.': 'Nagsi-sync ang mga mensahe sa shared SkillFlow development backend.',
  'Project conversation not found.': 'Hindi nakita ang project conversation.',
  'Portfolios are available to Student Designers.': 'Available ang mga portfolio sa Student Designers.',
  '+ Add': '+ Magdagdag',
  'Use only work you are allowed to share. Images are public on your profile.': 'Gumamit lamang ng gawa na pinahihintulutan kang ibahagi. Public sa profile ang mga larawan.',
  'Unable to add portfolio item': 'Hindi maidagdag ang portfolio item',
  'Please log in.': 'Mangyaring mag-log in.',
  'Please log in to view a profile.': 'Mag-log in para makita ang profile.',
  'Portfolio & Certifications': 'Portfolio at mga Sertipikasyon',
  'Manage': 'Pamahalaan',
  'Completed Work': 'Nakumpletong Gawa',
  'Add finished client projects as portfolio evidence.': 'Idagdag ang natapos na client project bilang portfolio evidence.',
  'Add': 'Magdagdag',
  'No services created yet.': 'Wala pang nagawang serbisyo.',
  'Client Reviews': 'Mga Review ng Kliyente',
  'Client Activity': 'Aktibidad ng Kliyente',
  'Profile not found.': 'Hindi nakita ang profile.',
  'Simulated student verification is complete for this academic demonstration.': 'Kumpleto ang simulated student verification para sa academic demonstration na ito.',
  'School details, student number, and ID sample remain private.': 'Nananatiling pribado ang school details, student number, at ID sample.',
  'No certifications listed.': 'Walang nakalistang sertipikasyon.',
  'No reviews yet': 'Wala pang review',
  'Manage this post': 'Pamahalaan ang post na ito',
  'Apply for this Job': 'Mag-apply sa Trabahong Ito',
  'Project post not found.': 'Hindi nakita ang project post.',
  'Skills Required': 'Mga Kailangang Kasanayan',
  'Close Proposals': 'Isara ang mga Proposal',
  'Open for Proposals': 'Bukas para sa mga Proposal',
  'Your proposal': 'Iyong proposal',
  'This project is not accepting proposals.': 'Hindi tumatanggap ng proposal ang proyektong ito.',
  'Withdraw Proposal': 'Bawiin ang Proposal',
  'Unable to submit proposal': 'Hindi maisumite ang proposal',
  'Open Student Verification': 'Buksan ang Student Verification',
  'No matching open projects': 'Walang tumugmang bukas na proyekto',
  'Try a different search or category.': 'Subukan ang ibang search o kategorya.',
  'Shared Project Bookings': 'Shared Project Bookings',
  'Your Project Posts': 'Iyong mga Project Post',
  'Your Proposals': 'Iyong mga Proposal',
  'No project bookings yet': 'Wala pang project booking',
  'An accepted proposal or service request will appear here and enter the shared delivery lifecycle.': 'Lalabas dito ang tinanggap na proposal o service request at papasok sa shared delivery lifecycle.',
  'Project booking not found.': 'Hindi nakita ang project booking.',
  'All funding and earnings shown in this project are simulated. No payment credentials or real transfers are used.': 'Simulated ang lahat ng funding at earnings sa proyektong ito. Walang payment credential o totoong transfer na ginagamit.',
  'Respond to Request': 'Tumugon sa Kahilingan',
  'The client reserved simulated funds. You can begin the project.': 'Nagreserba ang kliyente ng simulated funds. Maaari mo nang simulan ang proyekto.',
  'Waiting for the student to respond.': 'Hinihintay ang tugon ng estudyante.',
  'Demo funds are reserved. Waiting for the student to start work.': 'Nakareserba ang demo funds. Hinihintay na simulan ng estudyante ang trabaho.',
  'Choose a fictional payment method for this display-only checkout. No account details are needed and no money moves.': 'Pumili ng kathang-isip na payment method para sa display-only checkout. Walang account details na kailangan at walang perang gagalaw.',
  'Simulation only. This is not proof of payment.': 'Simulation lamang. Hindi ito patunay ng bayad.',
  'This request is closed. Create a new request if you want to restart the project.': 'Sarado na ang request na ito. Gumawa ng bagong request upang simulan muli ang proyekto.',
  'This project lifecycle is complete.': 'Kumpleto na ang project lifecycle na ito.',
  'No proposals yet': 'Wala pang proposal',
  'Demo verified Student Designer proposals will appear here.': 'Lalabas dito ang mga proposal ng Demo Verified Student Designer.',
  'This proposal list is available only to the project Client.': 'Available lamang sa kliyente ng proyekto ang proposal list na ito.',
  'Service not found.': 'Hindi nakita ang serbisyo.',
  'Delivery Time': 'Oras ng Paghahatid',
  'Demo only ? no real payment will be collected.': 'Demo lamang ? walang totoong bayad na kokolektahin.',
  'Current password': 'Kasalukuyang password',
  'New password': 'Bagong password',
  'Confirm new password': 'Kumpirmahin ang bagong password',
  'Full Name': 'Buong Pangalan',
  'Verification Code': 'Verification Code',
  'Recommended for You': 'Inirerekomenda para sa Iyo',
  'Browse Projects': 'Mag-browse ng mga Proyekto',
  'Deletion and reset': 'Pagtanggal at pag-reset',
  'Sample Student Number': 'Sample Student Number',
  'Move earlier': 'Ilipat nang mas maaga',
  'Move later': 'Ilipat nang mas huli',
  'Remove image': 'Tanggalin ang larawan',
  'Retry upload': 'Subukang muli ang upload',
  'Cancel upload': 'Kanselahin ang upload',
  'Project title': 'Pamagat ng proyekto',
  'UI/UX, Prototyping': 'UI/UX, Prototyping',
  'Reference Images': 'Mga Reference Image',
  'Service Cover': 'Cover ng Serbisyo',
  'Gallery Images': 'Mga Larawan sa Gallery',
  'e.g. 2 revisions': 'hal. 2 pagbabago',
  'Display name': 'Pangalan na ipapakita',
  'Image Attachment': 'Kalakip na Larawan',
  'My Portfolio': 'Aking Portfolio',
  'e.g. Graphics & Design': 'hal. Graphics at Design',
  'Portfolio Images': 'Mga Larawan sa Portfolio',
  'Earned': 'Kinita',
  'Projects Posted': 'Mga Na-post na Proyekto',
  'Open Accepted Project': 'Buksan ang Tinanggap na Proyekto',
  'Optional Work Samples': 'Opsyonal na mga Sample ng Gawa',
  'Go Home': 'Pumunta sa Home',
  'Requested Revision': 'Hiniling na Pagbabago',
  'Latest Delivery': 'Pinakabagong Delivery',
  'Add Completed Work to Portfolio': 'Idagdag ang Natapos na Gawa sa Portfolio',
  'Accept Request': 'Tanggapin ang Kahilingan',
  'Decline Request': 'Tanggihan ang Kahilingan',
  'Optional Delivery Images': 'Opsyonal na mga Larawan ng Delivery',
};

const LanguageContext = createContext<AppLanguage>('English');

export function LocalizationProvider({ children, language }: PropsWithChildren<{ language: AppLanguage }>) {
  return <LanguageContext.Provider value={language}>{children}</LanguageContext.Provider>;
}

export function useAppLanguage() { return useContext(LanguageContext); }

export function translateText(value: string, language: AppLanguage) {
  if (language === 'English') return value;
  const exact = filipino[value];
  if (exact) return exact;
  return value
    .replace(/(\d+) days\b/gi, '$1 araw')
    .replace(/(\d+) day\b/gi, '$1 araw')
    .replace(/^Client: /, 'Kliyente: ')
    .replace(/^Student: /, 'Estudyante: ')
    .replace(/^Verification: /, 'Pagpapatunay: ');
}

export function translateNode(node: ReactNode, language: AppLanguage): ReactNode {
  if (typeof node === 'string') return translateText(node, language);
  if (Array.isArray(node)) return node.map((item) => translateNode(item, language));
  return node;
}

export function useTranslation() {
  const language = useAppLanguage();
  return { language, t: (value: string) => translateText(value, language) };
}
