import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Alert, Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';

import { AppHeader, AppText, BottomNav, MobilePage, PrimaryButton } from '@/components/ui';
import { colors, contentPadding, shadow } from '@/constants/theme';
import { formatPeso } from '@/data/fixtures';
import { useSession } from '@/context/session';

export default function ProfileScreen() {
  const { addCompletedProjectToPortfolio, bookings, certifications, currentAccount, getCareerReadiness, homeRoute, messages, portfolioItems, profiles, reviews, services, verifications } = useSession();
  if (!currentAccount) return <MobilePage><AppHeader title="Profile" onBack={() => router.back()} /><View style={styles.center}><AppText>Please log in to view a profile.</AppText></View></MobilePage>;
  const profile = profiles.find((item) => item.accountId === currentAccount.id);
  const verification = verifications.find((item) => item.studentId === currentAccount.id);
  const ownPortfolio = portfolioItems.filter((item) => item.studentId === currentAccount.id);
  const ownCertifications = certifications.filter((item) => item.studentId === currentAccount.id);
  const ownServices = services.filter((item) => item.providerId === currentAccount.id);
  const ownProjects = bookings.filter((item) => item.clientId === currentAccount.id || item.studentId === currentAccount.id);
  const ownReviews = reviews.filter((item) => item.studentId === currentAccount.id);
  const earnings = currentAccount.role === 'student' ? bookings.filter((item) => item.studentId === currentAccount.id && ['completed', 'reviewed'].includes(item.status)).reduce((total, item) => total + item.budget, 0) : 0;
  const completedNotAdded = ownProjects.filter((item) => item.studentId === currentAccount.id && ['completed', 'reviewed'].includes(item.status) && !ownPortfolio.some((portfolio) => portfolio.sourceProjectId === item.id));
  const hasUnreadMessages = messages.some((message) => message.senderId !== currentAccount.id && !message.readBy.includes(currentAccount.id));
  const addProject = (projectId: string) => { const result = addCompletedProjectToPortfolio(projectId); Alert.alert(result.ok ? 'Added to portfolio' : 'Unable to add project', result.ok ? 'The completed work is now part of your portfolio.' : result.message); };
  const readiness = currentAccount.role === 'student' ? getCareerReadiness(currentAccount.id) : null;

  return (
    <MobilePage>
      <StatusBar style="light" />
      <AppHeader title="Profile" onBack={() => router.back()} right={<Pressable accessibilityRole="button" accessibilityLabel="Open settings" onPress={() => router.push('/settings')}><Ionicons name="settings-outline" size={25} color={colors.white} /></Pressable>} />
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.identity}><View style={styles.avatar}><Ionicons name={currentAccount.role === 'student' ? 'school' : 'person'} size={43} color={colors.red} /></View><AppText weight="bold" style={styles.name}>{currentAccount.name}</AppText><AppText style={styles.role}>{currentAccount.role === 'student' ? 'Student Designer' : 'Client'}</AppText>{currentAccount.role === 'student' ? <Pressable onPress={() => router.push('/verification')} style={[styles.verification, verification?.status === 'verified' && styles.verified]}><Ionicons name={verification?.status === 'verified' ? 'checkmark-circle' : 'shield-outline'} size={17} color={verification?.status === 'verified' ? colors.green : colors.burgundy} /><AppText weight="medium" style={styles.verificationText}>{verification?.status === 'verified' ? 'Verified Student' : `Verification: ${(verification?.status ?? 'not submitted').replace('_', ' ')}`}</AppText></Pressable> : null}</View>
        <View style={styles.card}><AppText weight="semibold" style={styles.heading}>About</AppText><AppText style={styles.copy}>{profile?.bio || 'No biography added yet.'}</AppText>{profile?.location ? <Info icon="location-outline" text={profile.location} /> : null}{profile?.organization ? <Info icon="business-outline" text={profile.organization} /> : null}{profile?.school ? <Info icon="school-outline" text={profile.school} /> : null}{profile?.program ? <Info icon="book-outline" text={`${profile.program}${profile.gradeLevel ? ` · ${profile.gradeLevel}` : ''}`} /> : null}{profile?.skills.length ? <View style={styles.skills}>{profile.skills.map((skill) => <View key={skill} style={styles.skill}><AppText style={styles.skillText}>{skill}</AppText></View>)}</View> : null}<PrimaryButton title="Edit Profile" onPress={() => router.push('/profile/edit')} style={{ marginTop: 18 }} /></View>

        {currentAccount.role === 'student' ? <>
          {readiness ? <Pressable onPress={() => router.push('/career-readiness')} style={styles.readiness}><View><AppText weight="semibold" style={styles.heading}>Career Readiness</AppText><AppText style={styles.copy}>{readiness.level} · View the transparent breakdown</AppText></View><View style={styles.readinessScore}><AppText weight="bold" style={styles.readinessValue}>{readiness.score}</AppText><AppText style={styles.readinessMax}>/100</AppText></View><Ionicons name="chevron-forward" size={22} color={colors.burgundy} /></Pressable> : null}
          <View style={styles.stats}><Stat value={String(ownPortfolio.length)} label="Portfolio" /><Stat value={String(ownServices.filter((item) => item.status === 'published').length)} label="Services" /><Stat value={formatPeso(earnings)} label="Earned" /></View>
          <View style={styles.card}><View style={styles.headingRow}><AppText weight="semibold" style={styles.heading}>Portfolio & Certifications</AppText><Pressable onPress={() => router.push('/portfolio/index')}><AppText weight="medium" style={styles.link}>Manage</AppText></Pressable></View><AppText style={styles.copy}>{ownPortfolio.length} portfolio item{ownPortfolio.length === 1 ? '' : 's'} · {ownCertifications.length} certification{ownCertifications.length === 1 ? '' : 's'}</AppText></View>
          {completedNotAdded.length ? <View style={styles.card}><AppText weight="semibold" style={styles.heading}>Completed Work</AppText><AppText style={styles.copy}>Add finished client projects as portfolio evidence.</AppText>{completedNotAdded.map((project) => <Pressable key={project.id} onPress={() => addProject(project.id)} style={styles.actionRow}><AppText weight="medium" style={{ flex: 1 }}>{project.title}</AppText><AppText weight="semibold" style={styles.link}>Add</AppText></Pressable>)}</View> : null}
          <View style={styles.card}><View style={styles.headingRow}><AppText weight="semibold" style={styles.heading}>My Services</AppText><Pressable onPress={() => router.push('/services/new')}><AppText weight="medium" style={styles.link}>Create</AppText></Pressable></View>{ownServices.length ? ownServices.map((service) => <Pressable key={service.id} onPress={() => router.push({ pathname: '/services/[serviceId]/edit', params: { serviceId: service.id } })} style={styles.actionRow}><View style={{ flex: 1 }}><AppText weight="medium">{service.title}</AppText><AppText style={styles.small}>{service.status}</AppText></View><Ionicons name="create-outline" size={21} color={colors.burgundy} /></Pressable>) : <AppText style={styles.copy}>No services created yet.</AppText>}</View>
          {ownReviews.length ? <View style={styles.card}><AppText weight="semibold" style={styles.heading}>Client Reviews</AppText>{ownReviews.map((review) => <View key={review.id} style={styles.review}><AppText weight="semibold">{review.rating}/5</AppText><AppText style={styles.copy}>{review.comment}</AppText></View>)}</View> : null}
        </> : <View style={styles.card}><AppText weight="semibold" style={styles.heading}>Client Activity</AppText><AppText style={styles.copy}>{ownProjects.length} project request{ownProjects.length === 1 ? '' : 's'} created in this local demonstration.</AppText></View>}
      </ScrollView>
      <BottomNav active="profile" onHome={() => router.replace(homeRoute)} onProjects={() => router.push('/projects/index')} onPortfolio={currentAccount.role === 'student' ? () => router.push('/portfolio/index') : undefined} onMessages={() => router.push('/messages/index')} onSaved={currentAccount.role === 'client' ? () => router.push({ pathname: '/marketplace', params: { saved: 'true' } }) : undefined} onProfile={() => undefined} messageUnread={hasUnreadMessages} variant={currentAccount.role === 'client' ? 'client' : 'student'} />
    </MobilePage>
  );
}

function Info({ icon, text }: { icon: 'location-outline' | 'business-outline' | 'school-outline' | 'book-outline'; text: string }) { return <View style={styles.info}><Ionicons name={icon} size={18} color={colors.burgundy} /><AppText style={styles.infoText}>{text}</AppText></View>; }
function Stat({ value, label }: { value: string; label: string }) { return <View style={styles.stat}><AppText weight="bold" style={styles.statValue}>{value}</AppText><AppText style={styles.small}>{label}</AppText></View>; }

const styles = StyleSheet.create({
  content: { padding: contentPadding, gap: 16, paddingBottom: 30 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, identity: { alignItems: 'center', paddingVertical: 10 }, avatar: { width: 92, height: 92, borderRadius: 46, backgroundColor: colors.blush, alignItems: 'center', justifyContent: 'center' }, name: { fontSize: 25, marginTop: 12 }, role: { color: colors.muted, fontSize: 12, marginTop: 2 }, verification: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 10, backgroundColor: colors.blush, borderRadius: 15, paddingHorizontal: 11, paddingVertical: 6 }, verified: { backgroundColor: colors.greenSoft }, verificationText: { color: colors.burgundy, fontSize: 10, textTransform: 'capitalize' }, card: { backgroundColor: colors.white, borderRadius: 14, padding: 17, ...shadow }, readiness: { minHeight: 88, flexDirection: 'row', alignItems: 'center', gap: 11, backgroundColor: colors.blush, borderRadius: 14, padding: 16 }, readinessScore: { flexDirection: 'row', alignItems: 'baseline' }, readinessValue: { color: colors.red, fontSize: 27 }, readinessMax: { color: colors.burgundy, fontSize: 9 }, heading: { fontSize: 17 }, headingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, copy: { color: colors.muted, fontSize: 12, lineHeight: 19, marginTop: 6 }, info: { flexDirection: 'row', alignItems: 'center', gap: 9, marginTop: 11 }, infoText: { fontSize: 12 }, skills: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 13 }, skill: { backgroundColor: colors.blush, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 5 }, skillText: { color: colors.burgundy, fontSize: 10 }, stats: { flexDirection: 'row', gap: 8 }, stat: { flex: 1, alignItems: 'center', backgroundColor: colors.white, borderRadius: 12, paddingVertical: 14, ...shadow }, statValue: { fontSize: 16 }, small: { color: colors.muted, fontSize: 9, textTransform: 'capitalize', marginTop: 2 }, link: { color: colors.burgundy, fontSize: 12 }, actionRow: { minHeight: 49, flexDirection: 'row', alignItems: 'center', borderTopWidth: 1, borderTopColor: colors.border, marginTop: 10, paddingTop: 10 }, review: { borderTopWidth: 1, borderTopColor: colors.border, marginTop: 10, paddingTop: 10 },
});
