import Ionicons from '@expo/vector-icons/Ionicons';
import { router, useLocalSearchParams } from 'expo-router';
import { ScrollView, StyleSheet, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';

import { AppHeader, AppText, MobilePage } from '@/components/ui';
import { colors, contentPadding, shadow } from '@/constants/theme';
import { Certification, PortfolioItem, ProjectReview, StudentVerification, useSession } from '@/context/session.remote';

export default function PublicProfileScreen() {
  const { userId } = useLocalSearchParams<{ userId: string }>();
  const { accounts, certifications, portfolioItems, profiles, projectPosts, reviews, verifications } = useSession();
  const account = accounts.find((item) => item.id === userId);
  const profile = profiles.find((item) => item.accountId === userId);
  const verification = verifications.find((item) => item.studentId === userId);
  const portfolio = portfolioItems.filter((item) => item.studentId === userId);
  const certs = certifications.filter((item) => item.studentId === userId);
  const userReviews = reviews.filter((item) => item.studentId === userId);
  if (!account) return <MobilePage><AppHeader title="Profile" onBack={() => router.back()} /><View style={styles.center}><AppText>Profile not found.</AppText></View></MobilePage>;
  const isClient = account.role === 'client';
  const projectsPosted = isClient ? projectPosts.filter((p) => p.clientId === userId).length : 0;
  const average = userReviews.length ? (userReviews.reduce((total, review) => total + review.rating, 0) / userReviews.length).toFixed(1) : '0';
  return <MobilePage><StatusBar style="light" /><AppHeader title={isClient ? 'Client Profile' : 'Student Profile'} onBack={() => router.back()} /><ScrollView contentContainerStyle={styles.content}><ProfileIdentity name={account.name} bio={profile?.bio} verified={verification?.status === 'verified'} isClient={isClient} /><View style={styles.stats}>{isClient ? <><Stat label="Projects Posted" value={String(projectsPosted)} /><View style={styles.statDivider} /></> : null}<Stat label="Rating" value={average} /><View style={styles.statDivider} />{!isClient ? <><Stat label="Portfolio" value={String(portfolio.length)} /><View style={styles.statDivider} /></> : null}<Stat label="Reviews" value={String(userReviews.length)} /></View>{!isClient ? <VerificationCard verification={verification} /> : null}{!isClient ? <PortfolioCard items={portfolio} /> : null}{!isClient ? <CertificationCard items={certs} /> : null}<ReviewsCard reviews={userReviews} /></ScrollView></MobilePage>;
}
function ProfileIdentity({ name, bio, verified, isClient }: { name: string; bio?: string; verified: boolean; isClient: boolean }) { return <View style={styles.identity}><View style={styles.avatar}><Ionicons name="person" size={45} color={colors.red} /></View><AppText weight="bold" style={styles.name}>{name}</AppText>{!isClient && verified ? <View style={styles.badge}><Ionicons name="checkmark-circle" size={17} color={colors.green} /><AppText weight="medium" style={styles.badgeText}>Verified Student</AppText></View> : null}<View style={styles.roleTag}><AppText style={styles.roleTagText}>{bio || (isClient ? 'Client' : 'Student Designer')}</AppText></View></View>; }
function VerificationCard({ verification }: { verification?: StudentVerification }) { if (verification?.status !== 'verified') return null; return <View style={styles.card}><AppText weight="semibold" style={styles.heading}>Student Verification</AppText><AppText style={styles.copy}>Simulated student verification is complete for this academic demonstration.</AppText><AppText style={styles.privacy}>School details, student number, and ID sample remain private.</AppText></View>; }
function PortfolioCard({ items }: { items: PortfolioItem[] }) { return <View style={styles.card}><AppText weight="semibold" style={styles.heading}>Portfolio</AppText>{items.length ? items.map((item) => <View key={item.id} style={styles.item}><AppText weight="medium">{item.title}</AppText><AppText style={styles.copy}>{item.description}</AppText></View>) : <AppText style={styles.copy}>No portfolio items yet.</AppText>}</View>; }
function CertificationCard({ items }: { items: Certification[] }) { return <View style={styles.card}><AppText weight="semibold" style={styles.heading}>Certifications</AppText>{items.length ? items.map((item) => <View key={item.id} style={styles.item}><AppText weight="medium">{item.name}</AppText><AppText style={styles.copy}>{item.issuer} · {item.year}</AppText></View>) : <AppText style={styles.copy}>No certifications listed.</AppText>}</View>; }
function ReviewsCard({ reviews }: { reviews: ProjectReview[] }) { return <View style={{ marginTop: 16 }}><AppText weight="semibold" style={styles.heading}>Reviews</AppText>{reviews.length ? reviews.map((review) => <View key={review.id} style={styles.item}><AppText weight="semibold">{review.rating}/5</AppText><AppText style={styles.copy}>{review.comment}</AppText></View>) : <View style={styles.emptyState}><Ionicons name="chatbubble" size={28} color={colors.muted} /><AppText style={styles.emptyText}>No reviews yet</AppText></View>}</View>; }
function Stat({ label, value }: { label: string; value: string }) { return <View style={styles.stat}><AppText weight="bold" style={styles.statValue}>{value}</AppText><AppText style={styles.statLabel}>{label}</AppText></View>; }
const styles = StyleSheet.create({ content: { padding: contentPadding, gap: 15, paddingBottom: 35 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, identity: { alignItems: 'center' }, avatar: { width: 100, height: 100, borderRadius: 50, backgroundColor: colors.blush, alignItems: 'center', justifyContent: 'center', borderWidth: 3, borderColor: colors.white, ...shadow }, name: { fontSize: 25, marginTop: 11 }, badge: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: colors.greenSoft, borderRadius: 15, paddingHorizontal: 10, paddingVertical: 5, marginTop: 7 }, badgeText: { color: colors.green, fontSize: 10 }, roleTag: { backgroundColor: colors.blush, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 5, marginTop: 8 }, roleTagText: { color: colors.burgundy, fontSize: 12 }, stats: { flexDirection: 'row', alignItems: 'center', marginTop: 8 }, stat: { flex: 1, alignItems: 'center', paddingVertical: 12 }, statDivider: { width: 1, height: 36, backgroundColor: colors.border }, statValue: { fontSize: 16, marginTop: 4 }, statLabel: { color: colors.muted, fontSize: 10, marginTop: 2 }, card: { backgroundColor: colors.white, borderRadius: 13, padding: 16, ...shadow }, heading: { fontSize: 17 }, copy: { color: colors.muted, fontSize: 11, lineHeight: 18, marginTop: 4 }, privacy: { color: colors.burgundy, fontSize: 9, lineHeight: 15, marginTop: 9 }, item: { borderTopWidth: 1, borderTopColor: colors.border, marginTop: 11, paddingTop: 11 }, emptyState: { alignItems: 'center', paddingVertical: 24, gap: 8 }, emptyText: { color: colors.muted, fontSize: 12 } });
