import Ionicons from '@expo/vector-icons/Ionicons';
import { router, useLocalSearchParams } from 'expo-router';
import { ScrollView, StyleSheet, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';

import { AppHeader, AppText, MobilePage } from '@/components/ui';
import { colors, contentPadding, shadow } from '@/constants/theme';
import { Certification, PortfolioItem, ProjectReview, StudentVerification, useSession } from '@/context/session.remote';

export default function PublicProfileScreen() {
  const { userId } = useLocalSearchParams<{ userId: string }>();
  const { accounts, certifications, portfolioItems, profiles, reviews, verifications } = useSession();
  const account = accounts.find((item) => item.id === userId);
  const profile = profiles.find((item) => item.accountId === userId);
  const verification = verifications.find((item) => item.studentId === userId);
  const portfolio = portfolioItems.filter((item) => item.studentId === userId);
  const certs = certifications.filter((item) => item.studentId === userId);
  const userReviews = reviews.filter((item) => item.studentId === userId);
  if (!account) return <MobilePage><AppHeader title="Profile" onBack={() => router.back()} /><View style={styles.center}><AppText>Profile not found.</AppText></View></MobilePage>;
  const average = userReviews.length ? (userReviews.reduce((total, review) => total + review.rating, 0) / userReviews.length).toFixed(1) : 'New';
  return <MobilePage><StatusBar style="light" /><AppHeader title="Student Profile" onBack={() => router.back()} /><ScrollView contentContainerStyle={styles.content}><ProfileIdentity name={account.name} bio={profile?.bio} verified={verification?.status === 'verified'} /><View style={styles.stats}><Stat label="Rating" value={average} /><Stat label="Portfolio" value={String(portfolio.length)} /><Stat label="Reviews" value={String(userReviews.length)} /></View><VerificationCard verification={verification} /><PortfolioCard items={portfolio} /><CertificationCard items={certs} /><ReviewsCard reviews={userReviews} /></ScrollView></MobilePage>;
}
function ProfileIdentity({ name, bio, verified }: { name: string; bio?: string; verified: boolean }) { return <View style={styles.identity}><View style={styles.avatar}><Ionicons name="person" size={45} color={colors.red} /></View><AppText weight="bold" style={styles.name}>{name}</AppText>{verified ? <View style={styles.badge}><Ionicons name="checkmark-circle" size={17} color={colors.green} /><AppText weight="medium" style={styles.badgeText}>Verified Student</AppText></View> : null}<AppText style={styles.bio}>{bio || 'Student Designer'}</AppText></View>; }
function VerificationCard({ verification }: { verification?: StudentVerification }) { if (verification?.status !== 'verified') return null; return <View style={styles.card}><AppText weight="semibold" style={styles.heading}>Student Verification</AppText><AppText style={styles.copy}>{verification.school}</AppText><AppText style={styles.copy}>{verification.program} · {verification.gradeLevel}</AppText><AppText style={styles.privacy}>The private student number and ID sample are never shown to clients.</AppText></View>; }
function PortfolioCard({ items }: { items: PortfolioItem[] }) { return <View style={styles.card}><AppText weight="semibold" style={styles.heading}>Portfolio</AppText>{items.length ? items.map((item) => <View key={item.id} style={styles.item}><AppText weight="medium">{item.title}</AppText><AppText style={styles.copy}>{item.description}</AppText></View>) : <AppText style={styles.copy}>No portfolio items yet.</AppText>}</View>; }
function CertificationCard({ items }: { items: Certification[] }) { return <View style={styles.card}><AppText weight="semibold" style={styles.heading}>Certifications</AppText>{items.length ? items.map((item) => <View key={item.id} style={styles.item}><AppText weight="medium">{item.name}</AppText><AppText style={styles.copy}>{item.issuer} · {item.year}</AppText></View>) : <AppText style={styles.copy}>No certifications listed.</AppText>}</View>; }
function ReviewsCard({ reviews }: { reviews: ProjectReview[] }) { if (!reviews.length) return null; return <View style={styles.card}><AppText weight="semibold" style={styles.heading}>Client Reviews</AppText>{reviews.map((review) => <View key={review.id} style={styles.item}><AppText weight="semibold">{review.rating}/5</AppText><AppText style={styles.copy}>{review.comment}</AppText></View>)}</View>; }
function Stat({ label, value }: { label: string; value: string }) { return <View style={styles.stat}><AppText weight="bold" style={{ fontSize: 18 }}>{value}</AppText><AppText style={styles.copy}>{label}</AppText></View>; }
const styles = StyleSheet.create({ content: { padding: contentPadding, gap: 15, paddingBottom: 35 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, identity: { alignItems: 'center' }, avatar: { width: 95, height: 95, borderRadius: 48, backgroundColor: colors.blush, alignItems: 'center', justifyContent: 'center' }, name: { fontSize: 25, marginTop: 11 }, badge: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: colors.greenSoft, borderRadius: 15, paddingHorizontal: 10, paddingVertical: 5, marginTop: 7 }, badgeText: { color: colors.green, fontSize: 10 }, bio: { color: colors.muted, textAlign: 'center', fontSize: 12, lineHeight: 19, marginTop: 9 }, stats: { flexDirection: 'row', gap: 8 }, stat: { flex: 1, alignItems: 'center', backgroundColor: colors.white, borderRadius: 12, padding: 13, ...shadow }, card: { backgroundColor: colors.white, borderRadius: 13, padding: 16, ...shadow }, heading: { fontSize: 17 }, copy: { color: colors.muted, fontSize: 11, lineHeight: 18, marginTop: 4 }, privacy: { color: colors.burgundy, fontSize: 9, lineHeight: 15, marginTop: 9 }, item: { borderTopWidth: 1, borderTopColor: colors.border, marginTop: 11, paddingTop: 11 } });
