import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';

import { AppHeader, AppText, FormField, MobilePage, PrimaryButton } from '@/components/ui';
import { colors, contentPadding, font, shadow } from '@/constants/theme';
import { formatPeso } from '@/data/fixtures';
import { useSession } from '@/context/session';

export default function ProjectPostDetailsScreen() {
  const { postId } = useLocalSearchParams<{ postId: string }>();
  const { accounts, bookings, currentAccount, projectPosts, proposals, setProjectPostStatus, submitProposal, verifications, withdrawProposal } = useSession();
  const post = projectPosts.find((item) => item.id === postId);
  const client = accounts.find((item) => item.id === post?.clientId);
  const myProposal = proposals.find((item) => item.projectPostId === postId && item.studentId === currentAccount?.id && item.status !== 'withdrawn');
  const booking = bookings.find((item) => item.projectPostId === postId);
  const verification = verifications.find((item) => item.studentId === currentAccount?.id);
  const [coverLetter, setCoverLetter] = useState(''); const [amount, setAmount] = useState(post ? String(post.budget) : ''); const [deliveryDays, setDeliveryDays] = useState('5');

  if (!post) return <MobilePage><StatusBar style="light" /><AppHeader title="Project" onBack={() => router.back()} /><View style={styles.missing}><AppText weight="semibold">Project post not found.</AppText></View></MobilePage>;
  const isOwner = currentAccount?.id === post.clientId;
  const sendProposal = () => { const result = submitProposal(post.id, { coverLetter, amount: Number(amount), deliveryDays: Number(deliveryDays) }); if (!result.ok) return Alert.alert(verification?.status !== 'verified' ? 'Verification required' : 'Unable to submit', result.message, verification?.status !== 'verified' ? [{ text: 'Cancel', style: 'cancel' }, { text: 'Verify Student Status', onPress: () => router.push('/verification') }] : undefined); Alert.alert('Proposal submitted', 'The client can now compare your proposal.'); };
  const changeStatus = (status: 'open' | 'closed' | 'archived') => { const result = setProjectPostStatus(post.id, status); Alert.alert(result.ok ? 'Project updated' : 'Unable to update', result.ok ? `Project is now ${status}.` : result.message); };
  return <MobilePage><StatusBar style="light" /><AppHeader title="Project Brief" onBack={() => router.back()} />
    <ScrollView contentContainerStyle={styles.content}>
      <View style={styles.statusRow}><View style={styles.status}><AppText weight="medium" style={styles.statusText}>{post.status.toUpperCase()}</AppText></View><AppText style={styles.deadline}>Deadline {post.deadline}</AppText></View>
      <AppText weight="bold" style={styles.title}>{post.title}</AppText><AppText weight="bold" style={styles.budget}>{formatPeso(post.budget)} budget</AppText>
      <Pressable onPress={() => client && router.push({ pathname: '/profiles/[userId]', params: { userId: client.id } })} style={styles.client}><View style={styles.avatar}><Ionicons name="business-outline" size={24} color={colors.burgundy} /></View><View style={{ flex: 1 }}><AppText weight="semibold">{client?.name ?? 'Client'}</AppText><AppText style={styles.muted}>{post.category}</AppText></View><Ionicons name="chevron-forward" size={20} color={colors.muted} /></Pressable>
      <AppText style={styles.description}>{post.description}</AppText>
      <View style={styles.skills}>{post.skills.map((skill) => <View key={skill} style={styles.skill}><AppText style={styles.skillText}>{skill}</AppText></View>)}</View>
      {booking ? <PrimaryButton title="Open Accepted Project" onPress={() => router.push({ pathname: '/projects/[projectId]', params: { projectId: booking.id } })} style={{ marginTop: 24 }} /> : null}
      {isOwner ? <View style={styles.panel}><AppText weight="semibold" style={styles.panelTitle}>Manage this post</AppText><PrimaryButton title={`View Proposals (${proposals.filter((item) => item.projectPostId === post.id && item.status !== 'withdrawn').length})`} onPress={() => router.push({ pathname: '/project-posts/[postId]/proposals', params: { postId: post.id } })} /><Pressable disabled={post.status === 'closed' || post.status === 'archived'} onPress={() => router.push({ pathname: '/project-posts/[postId]/edit', params: { postId: post.id } })} style={styles.secondary}><AppText weight="semibold" style={styles.secondaryText}>Edit Project</AppText></Pressable>{post.status === 'open' ? <Pressable onPress={() => changeStatus('closed')} style={styles.secondary}><AppText weight="semibold" style={styles.secondaryText}>Close Proposals</AppText></Pressable> : post.status === 'draft' || (post.status === 'closed' && !post.acceptedProposalId) ? <Pressable onPress={() => changeStatus('open')} style={styles.secondary}><AppText weight="semibold" style={styles.secondaryText}>Open for Proposals</AppText></Pressable> : null}<Pressable onPress={() => changeStatus('archived')} style={styles.archive}><AppText weight="semibold" style={{ color: colors.red }}>Archive Project</AppText></Pressable></View> : null}
      {currentAccount?.role === 'student' && !booking ? <View style={styles.panel}><AppText weight="semibold" style={styles.panelTitle}>Your proposal</AppText>{myProposal ? <><View style={styles.proposalStatus}><Ionicons name={myProposal.status === 'submitted' ? 'time-outline' : 'information-circle-outline'} size={21} color={colors.burgundy} /><View><AppText weight="semibold" style={styles.secondaryText}>{myProposal.status.replaceAll('_', ' ')}</AppText><AppText style={styles.muted}>{formatPeso(myProposal.amount)} · {myProposal.deliveryDays} days</AppText></View></View>{myProposal.status === 'submitted' ? <Pressable onPress={() => { const result = withdrawProposal(myProposal.id); Alert.alert(result.ok ? 'Proposal withdrawn' : 'Unable to withdraw', result.ok ? 'You may submit a new proposal while the post remains open.' : result.message); }} style={styles.archive}><AppText weight="semibold" style={{ color: colors.red }}>Withdraw Proposal</AppText></Pressable> : null}</> : post.status === 'open' ? <><AppText style={styles.hint}>{verification?.status === 'verified' ? 'Your verified status will be shown to the client.' : 'Simulated student verification is required before submission.'}</AppText><TextInput value={coverLetter} onChangeText={setCoverLetter} placeholder="Explain why you are a good fit…" placeholderTextColor={colors.muted} multiline style={styles.textArea} /><FormField icon="cash-outline" value={amount} onChangeText={setAmount} placeholder="Proposed amount" keyboardType="number-pad" /><View style={{ height: 10 }} /><FormField icon="alarm-outline" value={deliveryDays} onChangeText={setDeliveryDays} placeholder="Delivery days" keyboardType="number-pad" /><PrimaryButton title="Submit Proposal" onPress={sendProposal} style={{ marginTop: 14 }} /></> : <AppText style={styles.hint}>This project is not accepting proposals.</AppText>}</View> : null}
    </ScrollView>
  </MobilePage>;
}

const styles = StyleSheet.create({ content: { padding: contentPadding, paddingBottom: 36 }, missing: { flex: 1, alignItems: 'center', justifyContent: 'center' }, statusRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, status: { backgroundColor: colors.blush, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 }, statusText: { color: colors.burgundy, fontSize: 9 }, deadline: { color: colors.muted, fontSize: 10 }, title: { fontSize: 25, lineHeight: 33, marginTop: 16 }, budget: { fontSize: 20, color: colors.burgundy, marginTop: 8 }, client: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 22 }, avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.blush, alignItems: 'center', justifyContent: 'center' }, muted: { color: colors.muted, fontSize: 10, marginTop: 2 }, description: { fontSize: 14, lineHeight: 23, marginTop: 23 }, skills: { flexDirection: 'row', gap: 7, flexWrap: 'wrap', marginTop: 17 }, skill: { backgroundColor: colors.blush, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 6 }, skillText: { color: colors.burgundy, fontSize: 9 }, panel: { backgroundColor: colors.white, borderRadius: 14, padding: 15, marginTop: 25, gap: 10, ...shadow }, panelTitle: { fontSize: 17, marginBottom: 3 }, secondary: { minHeight: 46, borderWidth: 1, borderColor: colors.border, borderRadius: 8, alignItems: 'center', justifyContent: 'center' }, secondaryText: { color: colors.burgundy, textTransform: 'capitalize' }, archive: { minHeight: 42, alignItems: 'center', justifyContent: 'center' }, hint: { color: colors.muted, fontSize: 10, lineHeight: 16 }, textArea: { minHeight: 115, borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 12, fontFamily: font.regular, color: colors.ink, textAlignVertical: 'top' }, proposalStatus: { flexDirection: 'row', gap: 10, alignItems: 'center', backgroundColor: colors.blush, borderRadius: 10, padding: 12 } });
